import { useMemo, useState } from 'react';
import { ArrowUpRight, FileText, RotateCcw, ScanSearch, ShieldAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { parseClinicalNote, rankDifferential, type Finding } from '@/lib/clinical-intake';

export function ClinicalIntake({ onProfile, onDisease }: { onProfile: (ids: string[]) => void; onDisease: (id: string) => void }) {
  const [note, setNote] = useState('');
  const [findings, setFindings] = useState<Finding[] | null>(null);
  const matches = useMemo(() => rankDifferential(findings ?? []), [findings]);
  const analyze = () => { const result = parseClinicalNote(note); setFindings(result); onProfile(result.filter(f => !f.negated).map(f => f.id)); };
  const clear = () => { setNote(''); setFindings(null); onProfile([]); };
  return <section className="border-b border-border py-10" aria-label="Clinical intake">
    <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(340px,1fr)] lg:gap-12">
      <div><div className="mb-3 flex items-center gap-2 text-[10px] uppercase tracking-[.2em] text-primary"><span className="h-px w-5 bg-primary"/> Intake / 02</div><h2 className="font-display text-3xl md:text-4xl">Map a clinical story.</h2><p className="mt-3 max-w-lg text-sm leading-relaxed text-muted-foreground">Paste a de-identified symptom description or clinical note. Recognized features appear on the atlas as an exploratory overlay.</p><div className="mt-5 flex items-start gap-3 border-l-2 border-warning bg-secondary/40 p-4 text-xs leading-relaxed text-muted-foreground"><ShieldAlert className="mt-0.5 size-4 shrink-0 text-warning"/><span>Remove names, birth dates, addresses, and other identifiers before pasting. Notes stay in this browser tab and are not saved or sent to an AI service. This is not a diagnostic tool.</span></div><div className="mt-5"><label htmlFor="clinical-note" className="mb-2 block text-[10px] uppercase tracking-[.16em] text-muted-foreground">Clinical description</label><Textarea id="clinical-note" value={note} onChange={e => { setNote(e.target.value); if (findings) { setFindings(null); onProfile([]); } }} maxLength={12000} placeholder="Example: Child with recurrent seizures and developmental delay. No enlarged spleen." className="min-h-36 resize-y rounded-sm bg-secondary/40 p-4 text-sm leading-relaxed"/><div className="mt-3 flex flex-wrap items-center gap-2"><Button onClick={analyze} disabled={!note.trim()} className="gap-2 rounded-sm"><ScanSearch className="size-4"/> Map symptoms</Button><Button variant="ghost" onClick={clear} disabled={!note && !findings} className="rounded-sm text-muted-foreground"><RotateCcw className="size-3.5"/> Clear</Button><span className="ml-auto text-[11px] text-muted-foreground">{note.length.toLocaleString()} / 12,000</span></div></div></div>
      <div className="min-w-0 border-t border-border pt-5 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.18em] text-primary"><FileText className="size-3.5"/> Phenotype profile</div>{findings === null ? <div className="mt-8 border border-dashed border-border px-5 py-10 text-sm text-muted-foreground">Recognized HPO terms and exploratory matches will appear here.</div> : <><div className="mt-5 flex flex-wrap gap-2">{findings.length ? findings.map(f => <span key={f.id} className={`border px-2.5 py-2 text-xs ${f.negated ? 'border-border text-muted-foreground line-through' : 'border-primary/40 bg-primary/5 text-foreground'}`}>{f.label} <span className="ml-1 font-mono text-[10px] text-primary">{f.hpo}</span>{f.negated && <span className="ml-1 no-underline">· absent</span>}</span>) : <p className="text-sm text-muted-foreground">No supported HPO terms found in this demo vocabulary. Try describing seizures, developmental delay, ataxia, or enlarged spleen.</p>}</div>{matches.length > 0 && <><div className="mt-8 border-b border-border pb-3 text-[10px] uppercase tracking-[.16em] text-muted-foreground">Ranked overlap · not diagnostic probability</div><div>{matches.slice(0,5).map((match,i) => <Button key={match.id} variant="ghost" onClick={() => onDisease(match.id)} className="flex h-auto w-full items-start justify-between gap-3 rounded-none border-b border-border px-0 py-4 text-left hover:bg-transparent"><span className="min-w-0"><span className="block font-display text-lg text-foreground"><span className="mr-2 font-sans text-[10px] text-muted-foreground">0{i+1}</span>{match.label}</span><span className="mt-1 block whitespace-normal text-[11px] leading-relaxed text-muted-foreground">Mapped: {match.matched.join(', ')}{match.missing.length ? ` · Not mapped: ${match.missing.join(', ')}` : ''}</span></span><span className="flex shrink-0 items-center gap-1 font-mono text-xs text-primary">{match.score}<ArrowUpRight className="size-3"/></span></Button>)}</div><p className="mt-4 text-[11px] leading-relaxed text-muted-foreground">Scores are a simple overlap measure over four mapped features, not a diagnosis or likelihood. Missing atlas links are not evidence a condition lacks the symptom. Ask a qualified specialist for interpretation.</p></>}{findings.length > 0 && matches.length === 0 && <p className="mt-6 text-xs leading-relaxed text-muted-foreground">No supported match in this small atlas slice. That does not rule out any condition.</p>}</>}</div>
    </div>
  </section>;
}
